apiVersion: apps/v1
kind: Deployment
metadata:
  name: buymanagement
  labels:
    app: buymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buymanagement
  template:
    metadata:
      labels:
        app: buymanagement
    spec:
      containers:
        - name: buymanagement
          image: username/buymanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5